### PR TITLE
Update govt._scheme.css

### PR DESCRIPTION
**Pull request by tymsai**
This PR resolves the additional white space on hover
before
Untitled2
after
Untitled
applied changes can be viewed at
https://testsiteecell.netlify.app/

### CODE REVIEW

**Comment by tymsai** [comment]
@pixan198 @Sam-Ny  please review the changes

**Review by Sam-Ny — COMMENTED** [review]
Hey @tymsai , Thanks for the updates, looks good to me :white_check_mark:

**Comment by ashish11chawda** [comment]
Hey @tymsai 

Thanks for the suggestions on design

Can we cover the white card with blue one on hover, because after your changes the blue card is overflowing the white card and it seems fine on desktop but taking too much space on mobile devices

**Comment by tymsai** [comment]
> Hey @tymsai
> 
> Thanks for the suggestions on design
> 
> Can we cover the white card with blue one on hover, because after your changes the blue card is overflowing the white card and it seems fine on desktop but taking too much space on mobile devices

Okay will optimise it for mobile too

**Comment by tymsai** [comment]
@pixan198 Please give some screenshots as I am not able to reproduce the problem on my device

**Comment by ashish11chawda** [comment]
See here 👀

People usually don't like to scroll much and the website is already lengthy and this is contributing to that extra space

I'm not saying it is bad or something similar but see if you can reduce the padding keeping the aesthetics similar

**Comment by tymsai** [comment]
> 
> See here 👀
> 
> People usually don't like to scroll much and the website is already lengthy and this is contributing to that extra space
> 
> I'm not saying it is bad or something similar but see if you can reduce the padding keeping the aesthetics similar

Instead of sliding the blue box out of the white card, we can just display it on the main white card, it will save some space
like this
image

**Comment by ashish11chawda** [comment]
Yeah @tymsai 

This is better 🤩

Have you implemented it?

**Comment by ashish11chawda** [comment]
Hey @tymsai 

Update looks good to me ✅

But there's some issue with the cards with short height, the `more` button is not visible in this case.

Please have a look at attached screenshot


You'll have to override the CSS in this case to overflow the blue card

**Comment by tymsai** [comment]
> Update looks good to me ✅
> But there's some issue with the cards with short height, the `more` button is not visible in this case.

> You'll have to override the CSS in this case to overflow the blue card

Resolved the height problem in smaller cards.
https://testsiteecell.netlify.app/
other minor changes
1. Numbers shadow in ACHIEVEMENT section
2. Added border Radius to cards

**Review by ashish11chawda — APPROVED** [review]
LGTM ✅ 

- shadow of number images in the achievement section is 🔥 
- the fix for smaller cards could have been generalized instead of adding specific classes to selective HTML elements but this is fine too

**Pull request merged**
