### PR TITLE
updated logo

### PR DESCRIPTION
**Pull request by Ayan-thecodeking**
Screenshot (116)

### CODE REVIEW

**Review by Sam-Ny — COMMENTED** [review]
Hey @Ayan-thecodeking , please increase the size of the logo a little bit more.

**Review by Sam-Ny — COMMENTED** [review]
Hey @Ayan-thecodeking, the size of the logo seems fine but can we just decrease the top padding for the logo, we have so much blank space behind the contact us button.

Please refer to the original site.

**Comment by Ayan-thecodeking** [comment]
> Hey @Ayan-thecodeking, the size of the logo seems fine but can we just decrease the top padding for the logo, we have so much blank space behind the contact us button.
> 
> Please refer to the original site.

done sir

**Review by Sam-Ny — COMMENTED** [review]
Hey @Ayan-thecodeking, everything looks fine, Thanks!

**Pull request merged**
