### PR TITLE
Added Core Members in New Page, and team detail added

### PR DESCRIPTION
**Pull request by anurag-b72**
Review the code and get a merge. :-)
All Core Members of E-Cell added and in Team Pages, team detail has been added,

### CODE REVIEW

**Review by ECell-SSTC — CHANGES_REQUESTED** [review]
Hey @anurag-b72 , Impressive work! :star_struck: . But there are some changes that needs to be done :-

1. Design mobile view.
2. Use IDs and smooth scrolling for traversing to each section.

For Eg. Whenever we click "Meet the Team" button it should automatically scroll to the respective team section in external team page. Refer event section carousel for more details.

**Review by ashish11chawda — CHANGES_REQUESTED** [review]
Hey @anurag-b72 

Great work!

Your description cards and headings of team page is breaking in Mobile view, see screenshot below


Also a suggestion, instead of writing graduation years for present team members, write `present` it looks better and helps user to quickly identify current responsible person.

**Review by anurag-b72 — COMMENTED** [review]
I have made the page quite responsive for **mobile view**, and all Active members' activity status is shown by _"Present"_.  For _smooth scrolling_ of the Page, image size is reduced for the larger images.

**Review by ashish11chawda — APPROVED** [review]
LGTM

You can work on the team details section, it looks fine on desktop view (but still not utilising available space and contributing to more scrolling for user) but for Mobile view it looks little off as the text is centred and text doens't have enough space to form atleast 3 words in a row so maybe you can try to increase width currently it is 40vw i guess, you can try to increase it to 60vw of 70vw, i don't know how it'll look but try these things and let me know if it turns out good

Also the shadow of the box for description is not in phase with the over style of the team page you can also experiment with different colors like the blue we're already using in user cards so that it gives a unified experience to the user

**Review by anurag-b72 — COMMENTED** [review]
Team-detail **width increased**, _font size_ is adjusted accordingly.

**Review by ECell-SSTC — APPROVED** [review]
Everything looks good to me, great work thanks :handshake: .

**Pull request merged**
